export const projects = [
  {
    image: "public/image/travelpng.jpg",
    title: "Travel Booking System",
    subtitle: "MYSQL",
    handle: "Github Link👈",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/sangeethaa-dev/Sql-project",
  },
  {
    image: "public/image/taskmanagement.jpg",
    title: "Task-Management",
    subtitle: "React js, Tailwind CSS",
    handle: "Live Link👈",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://sangeethaa-dev.github.io/Taskify/",
  },
  {
    image: "public/image/snakegame.png",
    title: "Snake Game",
    subtitle: "HTML, CSS, and JavaScript",
    handle: "Live Link👈",
    borderColor: "#F59E0B",
    gradient: "linear-gradient(210deg, #F59E0B, #000)",
    url: "https://sangeethaa-dev.github.io/SnakeGame/",
  },
  {
    image: "public/image/ecommerce.jpg",
    title: "E-Commerce",
    subtitle: "React js , Tailwind CSS",
    handle: "Github Link👈",
    borderColor: "#EF4444",
    gradient: "linear-gradient(195deg, #EF4444, #000)",
    url: "https://github.com/sangeethaa-dev/Zaptro-yt",
  },
  {
    image: "public/image/3in1.png",
    title: "3 in 1 Project",
    subtitle: "HTML, CSS, JavaScript",
    handle: "Live Link👈",
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(160deg, #8B5CF6, #000)",
    url: "https://sangeethaa-dev.github.io/calculator/",
  },
  {
    image: "public/image/productmanagement.jpg",
    title: "Product Sales",
    subtitle: "SpringBoot, Html, Tailwind CSS",
    handle: "Github Link👈",
    borderColor: "#EC4899",
    gradient: "linear-gradient(175deg, #EC4899, #000)",
    url: "https://github.com/sangeethaa-dev/ProductSales",
  },
  {
    image: "public/image/hotelbooking.jpg",
    title: "Hotel Booking",
    subtitle: "React js, Tailwind CSS",
    handle: "Github Link👈",
    borderColor: "#EC4899",
    gradient: "linear-gradient(175deg, #EC4899, #000)",
    url: "https://github.com/sangeethaa-dev/HotelBooking",
  },
  {
    image: "public/image/bookstore.jpg",
    title: "Book Store",
    subtitle: "SpringBoot, Html, Tailwind CSS",
    handle: "Github Link👈",
    borderColor: "#EC4899",
    gradient: "linear-gradient(175deg, #EC4899, #000)",
    url: "https://github.com/sangeethaa-dev/BookStore",
  },
];
